//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOrder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelOrderEntities : DbContext
    {
        public HotelOrderEntities()
            : base("name=HotelOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionDescribe> ActionDescribe { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityReference> ActivityReference { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<DiscountReference> DiscountReference { get; set; }
        public virtual DbSet<HotelFacilities> HotelFacilities { get; set; }
        public virtual DbSet<HotelIndustries> HotelIndustries { get; set; }
        public virtual DbSet<HotelRegionName> HotelRegionName { get; set; }
        public virtual DbSet<MultipleHotelFacilities> MultipleHotelFacilities { get; set; }
        public virtual DbSet<MultipleRoomFacilities> MultipleRoomFacilities { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderDetailStatus> OrderDetailStatus { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderSpecialRequest> OrderSpecialRequest { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomAdmin> RoomAdmin { get; set; }
        public virtual DbSet<RoomClass> RoomClass { get; set; }
        public virtual DbSet<RoomFacilities> RoomFacilities { get; set; }
        public virtual DbSet<RoomImage> RoomImage { get; set; }
        public virtual DbSet<RoomMember> RoomMember { get; set; }
        public virtual DbSet<RoomStyle> RoomStyle { get; set; }
        public virtual DbSet<RoomTimePrice> RoomTimePrice { get; set; }
        public virtual DbSet<SpecialRequest> SpecialRequest { get; set; }
    }
}
