//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelIndustries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelIndustries()
        {
            this.MultipleHotelFacilities = new HashSet<MultipleHotelFacilities>();
            this.Room = new HashSet<Room>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelPhone { get; set; }
        public Nullable<int> HotelRegionID { get; set; }
        public string HotelAddress { get; set; }
        public byte[] HotelImage { get; set; }
        public string HotelImageDiscription { get; set; }
    
        public virtual HotelRegionName HotelRegionName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultipleHotelFacilities> MultipleHotelFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
    }
}
