//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetails()
        {
            this.OrderSpecialRequest = new HashSet<OrderSpecialRequest>();
        }
    
        public string OrderDetailID { get; set; }
        public string OrderID { get; set; }
        public Nullable<System.DateTime> MoveInDate { get; set; }
        public Nullable<System.DateTime> MoveOutDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<decimal> PaymentPrice { get; set; }
        public Nullable<int> OrderDetailStatusID { get; set; }
        public string RoomID { get; set; }
        public string OrderDetailRemark { get; set; }
    
        public virtual OrderDetailStatus OrderDetailStatus { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Payments Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSpecialRequest> OrderSpecialRequest { get; set; }
    }
}
