//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomMember()
        {
            this.ActionDescribe = new HashSet<ActionDescribe>();
            this.Comments = new HashSet<Comments>();
            this.DiscountReference = new HashSet<DiscountReference>();
            this.Orders = new HashSet<Orders>();
        }
    
        public string AdminID { get; set; }
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> MemberBirthday { get; set; }
        public string MemberGender { get; set; }
        public string MemberIdentity { get; set; }
        public string MemberPhone { get; set; }
        public string MemberEMail { get; set; }
        public byte[] MemberPhoto { get; set; }
        public string MemberPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionDescribe> ActionDescribe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountReference> DiscountReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual RoomAdmin RoomAdmin { get; set; }
    }
}
