//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.MultipleRoomFacilities = new HashSet<MultipleRoomFacilities>();
            this.RoomImage = new HashSet<RoomImage>();
        }
    
        public string RoomID { get; set; }
        public string RoomClassID { get; set; }
        public Nullable<int> RoomSize { get; set; }
        public Nullable<int> RoomPeople { get; set; }
        public string RoomStyleID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string RoomStatus { get; set; }
        public string AdminID { get; set; }
        public Nullable<int> favorite { get; set; }
    
        public virtual HotelIndustries HotelIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultipleRoomFacilities> MultipleRoomFacilities { get; set; }
        public virtual RoomAdmin RoomAdmin { get; set; }
        public virtual RoomClass RoomClass { get; set; }
        public virtual RoomStyle RoomStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImage> RoomImage { get; set; }
    }
}
